import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import sitemap from 'vite-plugin-sitemap'

const routes = [
  '/',
  '/about',
  '/contact',
  '/blog',
  '/galleries',
  '/faq',
  '/engagements',
  '/ski',
  '/headshots',
  '/store',
  '/vendors-list',
  '/become-vendor',
  '/privacy-policy',
  // posts do blog
  '/blog/surprise-proposal',
  '/blog/touch-my-melody-lingerie',
  '/blog/winter-family-portraits',
  '/blog/proteus-gathering',
  '/blog/moutain-proposal-luxury-picnic',
  '/blog/lovezone-community-jam',
  '/blog/winter-park',
  '/blog/eloping-with-snow',
  '/blog/surprise-engagement-rocky-mountain',
  '/blog/surprise-engagement-lily-lake',
  '/blog/surprise-engagement-san-sophia',
  '/blog/engagement-rings',
  '/blog/surprise-engagement-fort-collins',
  '/blog/black-tie-engagement-session',
  '/blog/surprise-proposal-botanic-gardens',
  '/blog/family-photograph-session-at-maroon-bells',
  '/blog/k-signature-headshot',
  '/blog/j-snowboarding-experience',
  '/blog/preparing-for-headhost-session',
  '/blog/family-portraits-with-adults-chindren-and-partners',
  '/blog/e+b-engagement',
  '/blog/j+a-engagement',
  '/blog/eldora-resort-park-girls-rail-jam',
  '/blog/family-reunion-at-sapphire-point-overlook',
  '/blog/casula-colorful-portrait-session',
  '/blog/spring-portrait-session-at-lily-lake',
  '/blog/graduation-session-panama-city-beach',
  '/blog/laid-back-mens-portrait-session-nederland',
  '/blog/jaded-beauty',
  '/blog/bringing-memories-to-light',
  '/blog/branding-photoshoot-in-denver',
  '/blog/proposing-at-lily-lake-colorado',
  '/blog/ready-for-a-branding-shoot',
  '/blog/family-holiday-at-sapphire-point',
  '/blog/outdoor-vibes-or-studio',
  '/blog/get-ready-for-brading-shoot',
  '/blog/new-hairstylist-meesha',
  '/blog/how-to-get-ready-to-dating-photo-session',
  '/blog/professional-photos-for-dating-profile',
  '/blog/basketball-tournament',
  '/blog/how-to-use-branding-to-attract-clients',
  '/blog/what-to-wear-for-outdoor-photoshoot',
  '/blog/i70-terrain-park-keystone-resort-snowboard-snow-experience-session',
  '/blog/galentines-day-ladies-rail-jam',
  '/blog/ruby-hill-park-winter-denver-2025',
  '/blog/how-to-use-your-client-gallery',
  '/blog/valentines-day-galentines-day-denver-2025',
  '/blog/snowboarding-keystone-resort-24-25-snow-experience-park-jumps-tricks',
  '/blog/engagement-photos-dillon-loveland-lake-pass',
  '/blog/moutainboarding-colorado-sports',
  '/blog/dog-portraits-lafayette-park',
  '/blog/engagement-proposal-surprise-denver-colorado',
  '/blog/klein-family-portraits-bear-lake-moraine-park',
  '/blog/engagement-proposal-RMNP-bear-lake',
  '/blog/maternity-photography-session-boulder-lost-gulch',
  '/blog/family-portraits-photography-lakewood-colorado-belmar-park',
  '/blog/maternity-photography-session-genesee-park-golden-hour',
  '/blog/outdoor-portraits-photography',
  '/blog/photography-permits-Hildebrand-Ranch-Park-Colorado',
  '/blog/tall-photographer-why-height-important',
  '/blog/portraits-dillon-breckenridge-keystone-ski-snowboard-trip-colorado',
  '/blog/preparing-for-photography-session-get-ready-portrait',
  '/blog/maternity-lakewood-park-colorado-session-kbphotograph',
  '/blog/wedding-photography',
  '/blog/headshots-downtown-denver',
  '/blog/maternity-lakewood-park-co',
  '/blog/landscapes',
  '/blog/headshots-khi',
  '/blog/donna-snowboarding-session',
  '/blog/flavia-snowboarding-session',
  '/blog/keystone-resort-documentary-photograph',
  '/blog/pets-photograph',
  '/blog/nettie-fitness-photograph',
  '/blog/sam-fitness-photograph',
  '/blog/brad-fitness-photograph',
  '/blog/wedding-engagement-photographer-in-estes-park-rocky-moutain-national-park',
  '/blog/what-to-wear-surprise-engagement-proposal-colorado',
  '/blog/garden-of-the-gods-elopement-guide-colorado-springs',
  '/blog/colorado-springs-elopement-stays-for-airbnb-and-vrbo-weddings',
  '/blog/troll-breckenridge-locations-explore',
  '/blog/loveland-pass-elopement-guide-colorado-wedding-locations',
  '/blog/how-to-elope-in-colorado-even-from-out-of-state',
  '/blog/elopement-hiking-boots-guide-colorado',
]

export default defineConfig({
  base: '/',
  plugins: [
    react(),
    sitemap({
      hostname: 'https://kbphotographer.com',
      dynamicRoutes: routes,
    })
  ]
})