export const REDIRECTS = {
  '/galleries.html': '/galleries',
  '/Portfolio.html': '/galleries',
  '/contact.html': '/contact',
  '/investment.html': '/',
  '/lifestyle.html': '/',
  '/store.html': '/store',
  '/become_a_vendor.html': '/become-vendor',
  '/Categories/faq.html': '/faq',
  '/Categories/blog.html': '/blog',
  '/Categories/PCB_photo_session.html': '/blog',
  '/Blog/dating_app_profile_picture.html': '/blog/professional-photos-for-dating-profile',
  '/Blog/tall_photographer_why_height_important.html': '/blog/tall-photographer-why-height-important',
  '/Blog/family_portraits_maroon_bells_colorado.html': '/blog/family-photograph-session-at-maroon-bells',
  '/Blog/family_photos_holiday_photoshoot_session_memories_snow_experience_summit_county': '/blog/family-holiday-at-sapphire-point',
  '/Blog/i70-terrain-park-keystone-resort-snowboard-snow-experience-session.html': '/blog/i70-terrain-park-keystone-resort-snowboard-snow-experience-session',
  '/Blog/k_j_signature_headshot_mini_session_broomfield.html': '/blog/k-signature-headshot',
  '/ski/': '/ski',
  '/about/': '/about',
  '/contact/': '/contact',
  '/engagements': '/engagements',
  '/pt/': '/pt',
  '/pt': '/pt',
}